name: CraftSonic
version: 0.2
main: com.swordpvp.craftsonic.CraftSonic
author: CraftThatBlock
depend: [SwordLib, CTBAPI, BarAPI, WorldEdit]
commands:
  craftsonic:
    description: CraftSonic' Commands
    aliases: [cs, sonic]
permissions:
  craftsonic.*:
    description: Gives access to all of CraftSonic
    children:
      craftsonic.admin: true
    default: OP
  craftsonic.admin:
    description: Gives admin access to CraftSonic
    default: OP